name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Linter
      run: |
        # Find and lint all Python files, but continue even if some files have errors
        find . -name "*.py" -exec flake8 {} \; || true
        echo "Python linting completed"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  

    - name: Install JSHint
      run: npm install -g jshint

    - name: Run Linter
      run: |
        # Find and lint all JavaScript files
        find . -name "*.js" -exec jshint {} \; || true
        echo "JavaScript linting completed"
